spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: orders-docs
              uri: http://order-service:8082
              predicates:
                - Path=/api/orders/v3/api-docs/**
            - id: accounts-docs
              uri: http://payment-service:8081
              predicates:
                - Path=/api/accounts/v3/api-docs/**
            - id: orders-api
              uri: http://order-service:8082
              predicates:
                - Path=/api/orders/**
            - id: accounts-api
              uri: http://payment-service:8081
              predicates:
                - Path=/api/accounts/**
springdoc:
  swagger-ui:
    urls:
      - name: Orders Service
        url: /api/orders/v3/api-docs
      - name: Payments Service
        url: /api/accounts/v3/api-docs